### ISSUE TITLE
Jobs always "Queued"

### ISSUE THREAD

**Issue by clrh** [omeka/plugin-OaipmhHarvester#19]
Hi,

I am new to Omeka, and trying to have oai plugins (harvest and repository).

When I add something to harvest, it stays in "queud", no error message, no status, no items in notices.

Configuration seems ok :
jobs.dispatcher.default = "Omeka_Job_Dispatcher_Adapter_Synchronous"
jobs.dispatcher.longRunning = "Omeka_Job_Dispatcher_Adapter_BackgroundProcess"

I see no error in logs (/var/log and application/logs/)

I don't know how to move forward in this problem, if someone can help me...

Thanks,
Claire.

**Comment by flotho** [comment]
Hi @clrh 

Did you solve this part ?

**Comment by clrh** [comment]
Sorry, I completely loose the focus on this. I close this issue.
